language: node_js
node_js:
  - "stable"
cache:
  directories:
    - front/node_modules
script:
  - cd front
#  - pwd
#  - ls -lah
  - yarn
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: front/build
  on:
    branch: master
