version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html
    environment:
      PHP_ENV: development
      DB_HOST: db
      DB_NAME: codeigniter_db
      DB_USER: user
      DB_PASSWORD: userpassword
      API_KEY:
      TOKEN: 123

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: codeigniter_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
