export const LOCAL_STORAGE_STATE = 'state';

export const API_BASE_URL = 'https://api.ttt.hitrov.com';
export const API_MOVE_URL = '/move';
export const API_CREATE_PLAYERS_URL = '/player/create_players';
export const API_GAME_URL = '/game';
export const API_HISTORY_URL = '/game/history';

export const MAX_RECENTS = 5;

export const ADD_RECENT_GAME = 'ADD_RECENT_GAME';

export const POST_MOVE_REQUEST = 'POST_MOVE_REQUEST';
export const POST_MOVE_SUCCESS = 'POST_MOVE_SUCCESS';
export const POST_MOVE_FAILURE = 'POST_MOVE_FAILURE';

export const SET_PLAYER_1_NAME = 'SET_PLAYER_1_NAME';
export const SET_PLAYER_2_NAME = 'SET_PLAYER_2_NAME';

export const SET_X_O = 'SET_X_O';

export const SET_BEARER_TOKEN = 'SET_BEARER_TOKEN';

export const POST_CREATE_PLAYERS_REQUEST = 'POST_CREATE_PLAYERS_REQUEST';
export const POST_CREATE_PLAYERS_SUCCESS = 'POST_CREATE_PLAYERS_SUCCESS';
export const POST_CREATE_PLAYERS_FAILURE = 'POST_CREATE_PLAYERS_FAILURE';

export const POST_CREATE_GAME_REQUEST = 'POST_CREATE_GAME_REQUEST';
export const POST_CREATE_GAME_SUCCESS = 'POST_CREATE_GAME_SUCCESS';
export const POST_CREATE_GAME_FAILURE = 'POST_CREATE_GAME_FAILURE';

export const FETCH_HISTORY_REQUEST = 'FETCH_HISTORY_REQUEST';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';
export const FETCH_HISTORY_FAILURE = 'FETCH_HISTORY_FAILURE';

export const DISMISS_ERROR = 'DISMISS_ERROR';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';

export const TOGGLE_PLAY_WITH_BOT = 'TOGGLE_PLAY_WITH_BOT';

export const PATH_HOME = '/';
export const PATH_GAME = '/game';
export const PATH_HISTORY = '/history';